[workspace]
authors = ["Swapneel Amit Pathak <swapiitr@gmail.com>"]
channels = ["conda-forge"]
name = "mesh-conversion"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
jupyterlab = ">=4.5.6,<5"
meshio = ">=5.3.5,<6"
pyvista = ">=0.47.3,<0.48"
